### ISSUE TITLE
Not able to upgrade the plan for plus

### ISSUE THREAD

**Issue by Tabassumbanu786** [IBM-Bluemix-Docs/account#18]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?
![Screen Shot 2019-04-30 at 10 05 35 AM](https://user-images.githubusercontent.com/35095108/56941078-aa852c00-6b2f-11e9-80c1-ac6062357f19.png)

**Comment by cjcarpen** [comment]
Thanks for opening this issue @Tabassumbanu786 ! For Watson Assistant, there are some additional actions needed for you to be able to change to the Plus service plan. Learn more here: https://cloud.ibm.com/docs/services/assistant?topic=assistant-upgrade

**Comment by Tabassumbanu786** [comment]
thanks @cjcarpen I tried this one also but not working for me

**Comment by cjcarpen** [comment]
For assistance upgrading to the Plus plan, please reach out to the Sales team here: https://ibm.biz/contact-WA-plus

We're working to update the information to include these links in the future.

**Comment by Tabassumbanu786** [comment]
we already coordinate with sales team but didn't get any response from last 15 days

**Comment by cjcarpen** [comment]
@Tabassumbanu786 I'm so sorry to hear that you've encountered delays! Please reach out to fredrik.tunvall@us.ibm.com, and he'll work with you directly to get your Watson Assistant service plan updated.

**Comment by Tabassumbanu786** [comment]
thanks for your kind help @cjcarpen for sharing the references it has help me out to complete my task

**Comment by cjcarpen** [comment]
Glad to hear it, @Tabassumbanu786 ! 😄 Closing this issue.
