### ISSUE TITLE
On signup in IBM cloud, "Enter a valid email address". Possible cause? Is it available in India?

### ISSUE THREAD

**Issue by kushshr** [IBM-Bluemix-Docs/account#19]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by cjcarpen** [comment]
Hi @kushshr ! IBM Cloud is available in India. To help troubleshoot why you might be seeing this error, please reach out to support here: https://watson.service-now.com/x_ibmwc_open_case_app.do#!/create

**Comment by cjcarpen** [comment]
Closing issue - let support take it from here! 😄
