### ISSUE TITLE
Update free account information

### ISSUE THREAD

**Issue by kKronstainBrown** [IBM-Bluemix-Docs/account#2]
Request from the containers OM:
can we update lite to free on this page and explain the paywall (or point to it in platform docs)?:
https://console.bluemix.net/docs/account/index.html#accounts

**Comment by cdmauney** [comment]
@kKronstainBrown Can you expand a little bit more on what you mean by "update lite to free"? Are you referring to the Lite account?

**Comment by kKronstainBrown** [comment]
@cdmauney I think he is under the impression that lite accounts are being renamed to free. But it could also be that he's confusing the account with container service clusters. Lite clusters were renamed to free clusters. I thought I'd throw it at you and see if you knew what he was talking about!

**Comment by cdmauney** [comment]
@kKronstainBrown Thanks for the background. Yes, I believe you're right about some confusion. Lite accounts aren't being renamed to free. Closing.
