### ISSUE TITLE
Managing users does not mention the service name

### ISSUE THREAD

**Issue by lionelmace** [IBM-Bluemix-Docs/account#3]
When seaching the docs with the keyword "manager+user", I get the following results.
First of all, I would expect the main page on how to manage user in the platform.
Then, the two results with "Managing Users" (see screenshot below) should mention the service. Otherwise I have to click on each link to figure out which service this documentation belongs to.

![image](https://user-images.githubusercontent.com/12241613/37343139-ebcd713a-26c6-11e8-8764-4491da9b1fb4.png)

**Comment by mekaufman** [comment]
This is a search issue. I'm going to open this in the /docs issue board where this can be prioritized and addressed. https://github.ibm.com/Bluemix/docs/issues/2524
