### ISSUE TITLE
Deleting Watson studio lite instance to create a new one.

### ISSUE THREAD

**Issue by Viraculous** [IBM-Bluemix-Docs/account#31]
"You can have only one instance of a Lite plan per service. To create a new instance, delete your existing Lite plan instance."
I get that warning whenever I try creating a Watson studio lite. I need help.

**Comment by hlucey** [comment]
@Viraculous 
Hey, do you have an existing instance? To find out, go to https://cloud.ibm.com/resources.

**Comment by Viraculous** [comment]
This issue has been resolved. Thanks
