### ISSUE TITLE
We donot support org deletion

### ISSUE THREAD

**Issue by wangmeng** [IBM-Bluemix-Docs/account#32]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
https://cloud.ibm.com/docs/account?topic=account-orgupdates&locale=en
In this page, it mentioned `To delete an org, contact Support`
It has been a while from BSS aspect, we don't support org deletion from billing/metering aspect. Could you please remove the description. 

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-orgupdates&locale=en

3. Do you have a suggestion about how to resolve the issue?
It has been a while from BSS aspect, we don't support org deletion from billing/metering aspect. Could you please remove the description.

**Comment by cjcarpen** [comment]
@wangmeng Updates are now showing in the doc here! https://cloud.ibm.com/docs/account?topic=account-orgupdates&locale=en
