### ISSUE TITLE
Account Pending problem at cloud.ibm.com

### ISSUE THREAD

**Issue by alexvoyatzis** [IBM-Bluemix-Docs/account#34]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
I'm Alexandros Vogiatzis from IBM GBS Greece.
I tried to create an account at cloud.ibm.com at the past but I never received any activation email.
I tried it again a couple of days ago and when logged in got a message saying that my account is pending, try to resend activation email or contact cloud support.
By clicking resend nothing happens.
At IBM Cloud Support I cannot create a case because my account is inactive.
I chat with help@IBM and the agent suggested to send you an email.

Can you please help me on this?
I remember that I never received any activation emails regarding other IBM services too in the past, if this means something...

![image](https://user-images.githubusercontent.com/11824424/61788834-c12fdc00-ae1b-11e9-8569-204d00655e95.png)

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by cjcarpen** [comment]
@alexvoyatzis I reached out to you internally for more info.

**Comment by cjcarpen** [comment]
Issue resolved!
