### ISSUE TITLE
test

### ISSUE THREAD

**Issue by edolce62** [IBM-Bluemix-Docs/account#41]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by cjcarpen** [comment]
Yup, this works! We're here to help resolve any issues with the IBM Cloud documentation. 😄

**Comment by cjcarpen** [comment]
I'm closing this issue for now, but if you come across any problems in the IBM Cloud documentation, feel free to open another issue!
